Re-added export for Props
ismamz/react-bootstrap-icons pull request #42
Opened 2022-09-09 19:19 UTC by AnimeAllstar

Interface export from [here](https://github.com/ismamz/react-bootstrap-icons/commit/c43ec0407ee4f49a0dee038eed0cc13427320d19) seems to have been undone in the latest version.

I also renamed "Props" to "IconProps" since a lot of people use "Props" for their own components. "IconProps" makes it easier to import without having to make other changes.

2022-09-09 19:53 UTC, AnimeAllstar commented
@ismamz

2022-09-27 20:19 UTC, ismamz commented
@AnimeAllstar I've updated the package and added the export for types. We can work on update the documentation for your use case that you have started on this PR.

2022-09-28 20:03 UTC, AnimeAllstar commented
@ismamz thanks for re-adding the exports. [This](https://github.com/ubccsss/content-manager/blob/d815c2ab94eea05892b78e9149a5a83512dbb5a6/src/components/Icon.tsx) is how I've used them in a project that I'm working on. 

I've updated the README after pulling the latest changes.

I also suggest changing the image in the README.md to:
![image](https://user-images.githubusercontent.com/39626451/192877453-9d5c67dd-37ea-4171-909a-cf91d4ed0a82.png)

From [here](https://icons.getbootstrap.com/).

The current image uses the old bootstrap purple, before the redesign.

2022-09-28 21:01 UTC, ismamz requested changes
@AnimeAllstar Looks great! I suggest some small changes.

2022-09-28 21:01 UTC, ismamz commented on README.md
>  - react-bootstrap-icons are open sourced ([MIT](https://github.com/ismamz/react-bootstrap-icons/blob/master/LICENSE.md))
```suggestion
- react-bootstrap-icons are open-sourced ([MIT](https://github.com/ismamz/react-bootstrap-icons/blob/master/LICENSE.md))
```

2022-09-28 22:08 UTC, AnimeAllstar commented on README.md
> +|size?|string \| number |size of the icon|
I think we should keep it `string \| number` since removing the backslash will confuse markdown into thinking that it is a column separator.

2022-09-29 13:05 UTC, ismamz commented
@AnimeAllstar thanks! 🙌

2022-09-29 13:06 UTC, ismamz approved these changes

2022-09-29 13:06 UTC, merged